# Generated by Django 4.2 on 2023-05-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=256)),
                ('titulo', models.CharField(max_length=256)),
                ('sub_titulo', models.CharField(max_length=256)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
