# Generated by Django 4.2 on 2023-05-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_alter_articulo_autor_alter_articulo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulo_imagenes'),
        ),
    ]
